/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotedRouteImport } from './routes/voted'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as EnterVoteCodeRouteImport } from './routes/enter-vote-code'
import { Route as AlreadyVotedRouteImport } from './routes/already-voted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const VotedRoute = VotedRouteImport.update({
  id: '/voted',
  path: '/voted',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterVoteCodeRoute = EnterVoteCodeRouteImport.update({
  id: '/enter-vote-code',
  path: '/enter-vote-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AlreadyVotedRoute = AlreadyVotedRouteImport.update({
  id: '/already-voted',
  path: '/already-voted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/already-voted': typeof AlreadyVotedRoute
  '/enter-vote-code': typeof EnterVoteCodeRoute
  '/manage': typeof ManageRoute
  '/vote': typeof VoteRoute
  '/voted': typeof VotedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/already-voted': typeof AlreadyVotedRoute
  '/enter-vote-code': typeof EnterVoteCodeRoute
  '/manage': typeof ManageRoute
  '/vote': typeof VoteRoute
  '/voted': typeof VotedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/already-voted': typeof AlreadyVotedRoute
  '/enter-vote-code': typeof EnterVoteCodeRoute
  '/manage': typeof ManageRoute
  '/vote': typeof VoteRoute
  '/voted': typeof VotedRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/already-voted'
    | '/enter-vote-code'
    | '/manage'
    | '/vote'
    | '/voted'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/already-voted'
    | '/enter-vote-code'
    | '/manage'
    | '/vote'
    | '/voted'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/already-voted'
    | '/enter-vote-code'
    | '/manage'
    | '/vote'
    | '/voted'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlreadyVotedRoute: typeof AlreadyVotedRoute
  EnterVoteCodeRoute: typeof EnterVoteCodeRoute
  ManageRoute: typeof ManageRoute
  VoteRoute: typeof VoteRoute
  VotedRoute: typeof VotedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voted': {
      id: '/voted'
      path: '/voted'
      fullPath: '/voted'
      preLoaderRoute: typeof VotedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter-vote-code': {
      id: '/enter-vote-code'
      path: '/enter-vote-code'
      fullPath: '/enter-vote-code'
      preLoaderRoute: typeof EnterVoteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/already-voted': {
      id: '/already-voted'
      path: '/already-voted'
      fullPath: '/already-voted'
      preLoaderRoute: typeof AlreadyVotedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlreadyVotedRoute: AlreadyVotedRoute,
  EnterVoteCodeRoute: EnterVoteCodeRoute,
  ManageRoute: ManageRoute,
  VoteRoute: VoteRoute,
  VotedRoute: VotedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
