/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VotedRouteImport } from './routes/voted'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as UploadWrestlersRouteImport } from './routes/upload-wrestlers'
import { Route as EnterVoteCodeRouteImport } from './routes/enter-vote-code'
import { Route as AlreadyVotedRouteImport } from './routes/already-voted'
import { Route as IndexRouteImport } from './routes/index'

const VotedRoute = VotedRouteImport.update({
  id: '/voted',
  path: '/voted',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadWrestlersRoute = UploadWrestlersRouteImport.update({
  id: '/upload-wrestlers',
  path: '/upload-wrestlers',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterVoteCodeRoute = EnterVoteCodeRouteImport.update({
  id: '/enter-vote-code',
  path: '/enter-vote-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AlreadyVotedRoute = AlreadyVotedRouteImport.update({
  id: '/already-voted',
  path: '/already-voted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/already-voted': typeof AlreadyVotedRoute
  '/enter-vote-code': typeof EnterVoteCodeRoute
  '/upload-wrestlers': typeof UploadWrestlersRoute
  '/vote': typeof VoteRoute
  '/voted': typeof VotedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/already-voted': typeof AlreadyVotedRoute
  '/enter-vote-code': typeof EnterVoteCodeRoute
  '/upload-wrestlers': typeof UploadWrestlersRoute
  '/vote': typeof VoteRoute
  '/voted': typeof VotedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/already-voted': typeof AlreadyVotedRoute
  '/enter-vote-code': typeof EnterVoteCodeRoute
  '/upload-wrestlers': typeof UploadWrestlersRoute
  '/vote': typeof VoteRoute
  '/voted': typeof VotedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/already-voted'
    | '/enter-vote-code'
    | '/upload-wrestlers'
    | '/vote'
    | '/voted'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/already-voted'
    | '/enter-vote-code'
    | '/upload-wrestlers'
    | '/vote'
    | '/voted'
  id:
    | '__root__'
    | '/'
    | '/already-voted'
    | '/enter-vote-code'
    | '/upload-wrestlers'
    | '/vote'
    | '/voted'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlreadyVotedRoute: typeof AlreadyVotedRoute
  EnterVoteCodeRoute: typeof EnterVoteCodeRoute
  UploadWrestlersRoute: typeof UploadWrestlersRoute
  VoteRoute: typeof VoteRoute
  VotedRoute: typeof VotedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voted': {
      id: '/voted'
      path: '/voted'
      fullPath: '/voted'
      preLoaderRoute: typeof VotedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-wrestlers': {
      id: '/upload-wrestlers'
      path: '/upload-wrestlers'
      fullPath: '/upload-wrestlers'
      preLoaderRoute: typeof UploadWrestlersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enter-vote-code': {
      id: '/enter-vote-code'
      path: '/enter-vote-code'
      fullPath: '/enter-vote-code'
      preLoaderRoute: typeof EnterVoteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/already-voted': {
      id: '/already-voted'
      path: '/already-voted'
      fullPath: '/already-voted'
      preLoaderRoute: typeof AlreadyVotedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlreadyVotedRoute: AlreadyVotedRoute,
  EnterVoteCodeRoute: EnterVoteCodeRoute,
  UploadWrestlersRoute: UploadWrestlersRoute,
  VoteRoute: VoteRoute,
  VotedRoute: VotedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
